<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/InceptionTools.Core/InceptionTools.Core.csproj" />
    <ProjectReference Include="../../src/CrescentHawksTools.Cli/CrescentHawksTools.Cli.csproj" />
  </ItemGroup>
</Project>
